Replace Mono.Options with CommandLineParser
planetarium/libplanet-explorer pull request #57
Opened 2019-08-19 16:48 UTC by dahlia

This patch replaces [Mono.Options] with [CommandLineParser], which is more declarative.

Also removed `-s`/`--store-type` option, because we no more use `FileStore` and have only `LiteDBStore`.

[Mono.Options]: https://github.com/xamarin/XamarinComponents/tree/master/XPlat/Mono.Options
[CommandLineParser]: https://github.com/commandlineparser/commandline

2019-08-20 05:11 UTC, longfin requested changes

2019-08-20 05:11 UTC, longfin commented on Libplanet.Explorer.Executable/Options.cs
> +}
```suggestion
}

```

2019-08-21 01:17 UTC, earlbread approved these changes

2019-08-21 02:53 UTC, limebell approved these changes

2019-08-21 02:53 UTC, longfin approved these changes

2019-08-21 02:54 UTC, merged